migrations/create_bouncer_tables.php
I was running into a bit of trouble rolling back this migration. It turns out the tables with the foreign key constraints need to be dropped first. I changed around the order so the down method now works properly.
Awesome plugin! :+1:
=> Changed table drop order in down function of create_bouncer_tables migration

readme.md, src/Clipboard.php, src/Conductors/ChecksRole.php, src/Database/HasRolesAndAbilities.php, tests/BouncerSimpleTest.php, tests/HasRolesAndAbilitiesTraitTest.php
This is a great package with excellent readability. In view of that, I've added some syntactic sugar to enhance the times when a user _doesn't_ have a particular role.
i.e.
```
if ($user->isNot('admin')) {
...
}
```
vs.
```
if (!$user->is('admin')) {
...
}
```
Like I said, simply some syntactic sugar. Also added some tests in.
=> Adding readability methods "not" and necessary tests

src/Database/Models.php
The function is being called statically.
I pulled down the latest version per conversation [here](https://github.com/JosephSilber/bouncer/issues/37) and noticed a quick fix. I didn't run the tests that are included in the repository.
=> Switch $this to self::

src/Middleware/Authorize.php
The IOC binding in Laravel uses the contract.  Currently this results in a:
```
Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> callable $userResolver ]] in class Illuminate\Auth\Access\Gate
```
Updating the import to utilize the contract allows the class to be correctly loaded out of the IOC container.
=> Updating Gate import to use the contract

src/CachedClipboard.php
The cache might return null (if the key doesn't exist) or an empty array (if the user doesn't have abilities). This change allows the getAbilitiesMethod to return an empty array from the cache in order to prevent multiple queries if the user doesn't have abilities.
=> Fixes #103 Issue with Cache

readme.md, src/BouncerServiceProvider.php
I find this much easier:
``` bash
$ php artisan vendor:publish --tag=bouncer.migrations
```
On an unrelated note: if I want to use 'groups' as well (e.g.: a user can have an ability because it either is member of a group or has a certain role) can I use this package without forking it?
=> Modified publishing migrations tag

readme.md
Removed version numbers from links, so the laravel website always redirects to the latest stable version.
=> Update laravel docs links

composer.json
update depencies
```"illuminate/auth": "5.1.20 - 5.5",
illuminate/container": "5.1.20 - 5.5",
"illuminate/contracts": "5.1.20 - 5.5",
"illuminate/database": "5.1.20 - 5.5"
"illuminate/cache": "5.1.20 - 5.5",
"illuminate/console": "5.1.20 - 5.5",
=> Update dependencies for laravel 5.5

src/BouncerServiceProvider.php
I am using:
Silber\Bouncer\Database\Models::setAbilitiesModel(MyAbility::class);
Silber\Bouncer\Database\Models::setRolesModel(MyRole::class);
but the BouncerServiceProvider is overwriting my custom values for Relation::morphMap()
ie, 
'roles' => MyRole::class
is being replaced by:
'roles' => Silber\Bouncer\Database\Role
=> use Models::classname() when running registerMorphs

src/Database/Ability.php, src/Database/Role.php
I ran into the issue that the properties were returned as strings from the database. (But only on the dedicated server at Siteground, not in localhost).
So I added typecasts fro non string attributes.
Is there a downside of adding these kind of typecasts?
-----
This might/will break custom UUID integrations into Bouncer, so users that use UUID have to override the `$cast` attribute
=> Adding typecasts for attributes

src/Database/Ability.php, src/Database/Role.php
'entity_id' is a column in abilities table, not roles. This PR puts its cast to the right model.
=> Fix "typo" in $casts

src/BouncerServiceProvider.php
The array_* helpers methods have been removed as of v6. This update changes the occurrences with the underlying Arr class methods.
=> Replace Laravel array helpers methods with Arr class methods

src/Database/Queries/Abilities.php, src/Database/Queries/Roles.php
Hi Joseph it's me again.
You once said version 1.0 would require Laravel 5.5+. So here is my WhereRaw to WhereColumn fix again. 
The main reason I keep pushing this change is when you use characters in your table prefix that should be escaped, the whereRaw approach breaks down. Also WhereColumn has been around since Laravel 5.2 so should be decent backwards compatibility imho.
=> Changed WhereRaw functions to Laravel 5.2's WhereColumn.

src/Database/Concerns/Authorizable.php, src/Database/Concerns/HasAbilities.php, src/Database/Concerns/HasRoles.php, src/Database/Concerns/IsRole.php, src/Database/HasRolesAndAbilities.php, tests/BaseTestCase.php
Since Laravel 5.3, [`Container::getInstance()` always returns an instance of the container](https://github.com/laravel/framework/pull/13111); if an instance hadn't been registered as a singleton, it registers a new one on the fly.
Since we no longer support older versions of Laravel, we can inline the `getInstance` call wherever we use it. This removes the need for precedence rules - both in Bouncer itself, and for [userland code](https://github.com/JosephSilber/bouncer/issues/465#issuecomment-588985901).
=> Remove the getClipboardInstance() methods

src/BouncerServiceProvider.php, src/Database/Models.php, src/Database/Queries/Abilities.php, src/Database/Queries/Roles.php
This is related to #372 
**Problem trying to solve**
`whereColumn` method already prepend table prefixes for columns.
This PR removes the duplicate prefix as it's currently produces db errors.
**Scenario**
PHP v7.4.3
Laravel v7.1.3
Bouncer v1.0.0-rc.7
Config (with database table prefix)
I didn't try Bouncer v1.0.0-rc.7 with Laravel v6, but currently the `whereColumn` method seems to be consistent with other database query grammer, and it's being prefixed as expected.
=> Fix #372 since whereColumn automatically prepend table prefix

src/Bouncer.php, tests/MultipleAbilitiesTest.php
This is to fix a bug in `canAny` method that is using the non-existing Gate `canAny` method. Use the  Gate `any` method instead.
I added the tests also.
=> Fix a bug on `canAny` that is using the non-existing Gate `canAny` method

readme.md
https://mariadb.com/kb/en/json-data-type/
I verified after an error with the debian 10.1 version of MariaDB
=> mariadb version for json data type

src/Console/CleanCommand.php
This fixes an issue where the clean command does not take into account morph mapped class names. Currently it will just take the entity_type value directly from the database without running it through the morph mapping.
=> Fix using morph mapped class names in CleanCommand

src/Console/CleanCommand.php
`entity_id` comparison to `*` is invalid (postgres would say: _Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "*"_).
`whereNotNull` above already takes care of the intent.
#446, #566
=> A fix for #446, #566

readme.md
This will save time, without having to remove `$` from the text copied by GitHub, or copying manually.
=> Remove $ from code snippet installing package

src/Database/Concerns/IsAbility.php, tests/ForbidTest.php
**Use case**
Ability attributes:
- `name` = `update-somemodel`
- `entity_type` = `App\SomeModel`
- `entity_id` = `0`
**Expected identifier attribute value**
`update-somemodel-app-somemodel-0`
**Actual identifier attribute value**
_without using typesafe checks_
`update-somemodel-app-somemodel`
Since
```php
if ($this->attributes['entity_id'])
```
will return `false` for `0` values.
**Long story short**
Using `0` as *id value* for an entity leads to wrong permissions checks (e.g. *forbid to update concrete model XY with id = `0`*)
=> Use typesafe checks when creating the ability identifier

src/BouncerFacade.php
Currently, I use Visual Studio Code, and as the facade does not have phpdoc, intellisense cannot identify the methods that are available on the facade.
However, when phpdoc is added to the facade, intellisense shows the available methods.
So, I decided to add PHPDoc on the facade.
=> Create PHPDoc in BouncerFacade

src/Database/Scope/Scope.php, tests/MultiTenancyTest.php
Fix #607. This has the expected behavior and not so eager to grant permissions when you may not want them to be granted.
=> Remove null checks and allow it to be queried

src/BouncerFacade.php, src/Conductors/Concerns/AssociatesAbilities.php
Continues on #638
Not sure if I missed any, but added default values to several facade methods.
Also, AssociatesAbilities::to accepts a string
=> Further docblock fixes
